[Settings]

[build]
  base = ""
  publish = "_site"
  command = "npm run build-prod"

[build.environment]
NODE_VERSION = "18.16.0"

[context.deploy-preview]
  command = "npm run build-prod"

[context.develop]
  command = "npm run build"
